import re
from playwright.sync_api import Page, expect, sync_playwright

# npx playwright codegen https://play.basketball-gm.com/l/1/trade --- for generating the UI functions (tools)

def test_example(page: Page) -> None:
    page.goto("https://play.basketball-gm.com/l/1/trade")
    page.get_by_role("link", name="Create a new league").click()
    page.get_by_role("button", name="Random").click()
    page.get_by_role("combobox").nth(2).select_option("real")
    page.get_by_role("button", name="Random").nth(1).click()
    page.get_by_role("button", name="Create League Processing").click()
    page.get_by_role("link", name="Trading Block").click()
    page.get_by_role("link", name="Trade", exact=True).click()
    page.get_by_role("link", name="Free Agents").click()
    page.get_by_role("button", name="Show players you can afford").click()
    page.get_by_role("cell", name="Pot").click()
    page.get_by_role("cell", name="Ovr").click()
    # page.get_by_role("row", name="5 James Bouknight  SG 25 47").get_by_role("button").nth(2).click()
    page.get_by_role("link", name="Trading Block").click()
    page.get_by_role("link", name="Trade Proposals").click()
    page.get_by_role("button", name="Negotiate").nth((1)).click()
    page.get_by_role("row", name="Exclude this player from counter offers 1 LaMelo Ball3PsV  PG 24 64 70 $40.77M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 0 Miles BridgesRV  F 27 63 64 $25M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 24 Brandon Miller 70 3  SF 23 56 64 $").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 2 Grant Williams 90 3  PF 27 56 56 $13").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 5 Mark WilliamsDiPoR  C 24 56 60 $6.").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 10 Josh Green  SG 25 52 55 $13.67M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 12 Josh Okogie  SG 27 51 51 $8M 2026 0").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 9 Wendell Moore Jr.  SG 24 48 59 $2.").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 11 Jusuf NurkićR  C 31 48 48 $18.75M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 25 KJ Simpson  PG 23 44 56 $600k 2025").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 8 Nick Smith Jr.  SG 21 44 61 $4.89M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 7 Damion Baugh  SG 25 42 47 $600k 2025").get_by_role("checkbox").first.check()
    page.locator("div:nth-child(4) > .col-xl-9 > .datatable-negative-margin-top > div > .table-responsive > .table > tbody > tr:nth-child(15) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 14 Moussa DiabatéR  C 23 42 54 $2.37M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 31 Tidjane Salaün  PF 20 42 63 $8.51M").get_by_role("checkbox").first.check()
    page.locator("div:nth-child(4) > .col-xl-9 > .datatable-negative-margin-top > div > .table-responsive > .table > tbody > tr:nth-child(18) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 1 LaMelo Ball3PsV  PG 24 64 70 $40.77M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 0 Miles BridgesRV  F 27 63 64 $25M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 24 Brandon Miller 70 3  SF 23 56 64 $").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 2 Grant Williams 90 3  PF 27 56 56 $13").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 5 Mark WilliamsDiPoR  C 24 56 60 $6.").get_by_role("checkbox").first.uncheck()
    page.locator("div:nth-child(4) > .col-xl-9 > .datatable-negative-margin-top > div > .table-responsive > .table > tbody > tr:nth-child(6) > td").first.click()
    page.locator("div:nth-child(4) > .col-xl-9 > .datatable-negative-margin-top > div > .table-responsive > .table > tbody > tr:nth-child(7) > td").first.click()
    page.locator("div:nth-child(4) > .col-xl-9 > .datatable-negative-margin-top > div > .table-responsive > .table > tbody > tr:nth-child(6) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 12 Josh Okogie  SG 27 51 51 $8M 2026 0").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 9 Wendell Moore Jr.  SG 24 48 59 $2.").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 11 Jusuf NurkićR  C 31 48 48 $18.75M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 25 KJ Simpson  PG 23 44 56 $600k 2025").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 8 Nick Smith Jr.  SG 21 44 61 $4.89M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 7 Damion Baugh  SG 25 42 47 $600k 2025").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 30 Seth Curry3  G 35 42 42 $2.09M 2025").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 14 Moussa DiabatéR  C 23 42 54 $2.37M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 31 Tidjane Salaün  PF 20 42 63 $8.51M").get_by_role("checkbox").first.uncheck()
    page.locator("div:nth-child(4) > .col-xl-9 > .datatable-negative-margin-top > div > .table-responsive > .table > tbody > tr:nth-child(18) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 3 DaQuan Jeffries  SG 28 40 42 $2.75M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 0 Tyrese Maxey3DpV  G 25 69 72 $40.77M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 21 Joel Embiid 80 BDiPo ...  C 31 66").get_by_role("checkbox").first.check()
    page.locator("tr:nth-child(3) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 20 Jared McCain 80 3V  G 21 55 67 $6.").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 8 Paul GeorgeV  GF 35 59 59 $52.9M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 28 Guerschon Yabusele3  FC 30 55 55 $2").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 65 Alex Reese  PF 26 48 51 $600k 2025").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 12 Jared Butler  G 25 48 53 $2.35M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 5 Andre DrummondR  C 32 46 46 $5M 2026").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 14 Ricky Council IV  GF 24 45 52 $2.").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 19 Justin Edwards  SF 22 45 58 $1.96M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 23 Eric Gordon3  GF 37 45 45 $3.39M").get_by_role("checkbox").first.check()
    page.locator("tr:nth-child(14) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 11 Jeff Dowtin  PG 28 43 43 $600k 2025").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 30 Adem Bona  FC 22 41 58 $2.25M 2028").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 16 Lonnie Walker IV  SG 27 40 42 $3M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 17 Jalen Hood-Schifino  SG 22 38 52 $3").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 16 Lonnie Walker IV  SG 27 40 42 $3M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 30 Adem Bona  FC 22 41 58 $2.25M 2028").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 17 Jalen Hood-Schifino  SG 22 38 52 $3").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 11 Jeff Dowtin  PG 28 43 43 $600k 2025").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 7 Kyle Lowry  PG 39 45 45 $2.09M 2025").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 23 Eric Gordon3  GF 37 45 45 $3.39M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 19 Justin Edwards  SF 22 45 58 $1.96M").get_by_role("checkbox").first.uncheck()
    page.locator("tr:nth-child(11) > td").first.click()
    page.locator("tr:nth-child(10) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 65 Alex Reese  PF 26 48 51 $600k 2025").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 12 Jared Butler  G 25 48 53 $2.35M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 9 Kelly Oubre Jr.  SF 30 54 54 $8.18M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 28 Guerschon Yabusele3  FC 30 55 55 $2").get_by_role("checkbox").first.uncheck()
    page.locator("tr:nth-child(5) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 8 Paul GeorgeV  GF 35 59 59 $52.9M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 9 Kelly Oubre Jr.  SF 30 54 54 $8.18M").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 5 Quentin Grimes3  SG 25 61 66 $4.3M").get_by_role("checkbox").first.uncheck()
    page.get_by_role("row", name="Exclude this player from counter offers 21 Joel Embiid 80 BDiPo ...  C 31 66").get_by_role("checkbox").first.uncheck()
    page.locator("tr:nth-child(2) > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 0 Tyrese Maxey3DpV  G 25 69 72 $40.77M").get_by_role("checkbox").first.uncheck()
    page.locator(".table-success > td").first.click()
    page.get_by_role("row", name="Exclude this player from counter offers 9 Wendell Moore Jr.  SG 24 48 59 $2.").get_by_role("checkbox").first.check()
    page.get_by_role("button", name="Propose trade").click()
    page.get_by_role("row", name="Exclude this player from counter offers 7 Damion Baugh  SG 25 42 47 $600k 2025").get_by_role("checkbox").first.check()
    page.get_by_role("row", name="Exclude this player from counter offers 7 Damion Baugh  SG 25 42 47 $600k 2025").get_by_role("checkbox").first.uncheck()
    page.get_by_role("link", name="James Bouknight").click() 
    page = context.new_page()
    page.goto("https://play.basketball-gm.com/l/1/trade")
    page.get_by_role("link", name="Create a new league").click()
    page.get_by_role("button", name="Create League Processing").click()
    page.get_by_role("link", name="Trade Proposals").click()
    page.get_by_role("button", name="Negotiate").first.click()
    page.get_by_role("button", name="What would make this deal").click()
    page.get_by_role("button", name="Propose trade").click()
    page.get_by_role("link", name="Trading Block").click()
    page.get_by_role("link", name="Free Agents").click()
    page.get_by_role("row", name="Tyreek Tiller  GF 20 28 52 0").get_by_role("button").nth(2).click()
    page.get_by_role("link", name="Trading Block").click()
    page.get_by_role("link", name="Trade Proposals").click()
    page.get_by_role("button", name="Negotiate").nth(1).click()
    page.get_by_role("link", name="Trading Block").dblclick()
    page.get_by_role("link", name="Trade Proposals").click()
    page.get_by_role("button", name="Negotiate").nth(2).click()


if __name__ == "__main__":
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=False)
        page = browser.new_page()
        test_example(page)
        browser.close()